{
 "title": "Microservices Log Monitoring Dashboard",
 "tags": [ "Microservice" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "FastAPI Errors Count",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"fastapi\"} |= \"Unprocessable Entity\" [1m])",
     "legendFormat": "FastAPI Errors"
    }
   ]
  },
  {
   "title": "Django Errors Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"django\"} |= \"Unprocessable Entity\" [1m])",
     "legendFormat": "Django Errors"
    }
   ]
  },
  {
   "title": "FastAPI Endpoints Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"fastapi\"} |= \"Request to access\" [1m])",
     "legendFormat": "FastAPI Endpoints"
    }
   ]
  },
  {
   "title": "Django Endpoints Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"django\"} |= \"Request to access\" [1m])",
     "legendFormat": "Django Endpoints"
    }
   ]
  },
  {
   "title": "FastAPI Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"fastapi\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Django Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"django\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FastAPI Errors (Unprocessable Entity)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"fastapi\"} |= \"Unprocessable Entity\"",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Django Errors (Unprocessable Entity)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"django\"} |= \"Unprocessable Entity\"",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FastAPI Endpoint Access",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{job=\"fastapi\"} |= \"Request to access\"",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Django Endpoint Access",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{job=\"django\"} |= \"Request to access\"",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}